### model
model_name_or_path: /data1/LLaMA-Factory/Meta-Llama-3-8B

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: config/deepspeed/ds_z3_config.json

### dataset
dataset: trump
cutoff_len: 256
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/pt
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 3.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
